[application]
host = "0.0.0.0"
port = 8000
[database]
username = "root"
password = "root"
port = 8001
host = "192.168.1.69"
database_name = "newsletter"
namespace = "zero2prod"
[email_client]
token = "20aa7675-3b54-4117-b7cb-288be8d2faf1"
base_url = "https://api.postmarkapp.com/"
sender = "mail@safira.club"

