pub mod configuration;
mod error;
pub mod routes;
pub mod startup;
pub use error::{AppError, Result};
mod models;
pub use models::*;
mod storage;
pub use storage::Storage;
pub mod telemetry;
mod validator;
pub use validator::validate_name;
mod email_client;
pub use email_client::EmailClient;
